### ISSUE TITLE
0.1.0 版本相关问题

### ISSUE THREAD

**Issue by icyblade** [icyblade/aleph#1]
**Def:** 第一个版本版本号为 0.1.0，对应原帖链接 [7.0.3.21491 - 7.0.3.21531 技能文本改动](http://bbs.ngacn.cc/read.php?tid=9244288)，对应原帖内容 [0.1.0.txt](https://github.com/icyblade/aleph/files/235870/0.1.0.txt)

经过一段时间对论坛用户以及部分版主的反馈观察，有如下问题需要改进，希望可以一起讨论一下
由于问题较多，所以这里就不开多个 issue 了
1.  去掉所有全能系数项 $@versadmg。例如：
   
   > 将你的怒气集中到下一次致死打击之中，使其额外造成[攻击强度_105/100_(1+$@versadmg)]点伤害，最多可叠加3次。不受公共冷却的影响。
2. 加一个纯中/英文判断：如果修改为全中文 -> 全英文或者全英文 -> 全中文，则不使用分词的方式做 diff，直接将前后两个列出来。例如：
   
   `[del][color=red]Pummels the target, interrupting spellcasting and preventing any spell in that school from being cast for [/color][/del][color=green]用拳头击打目标，打断其正在施放的法术，并使其在[/color]4[del][color=red]秒.[/color][/del][color=green]秒内不能施放该系法术。[/color]`
   
   修改为
   
   `[del][color=red]Pummels the target, interrupting spellcasting and preventing any spell in that school from being cast for 4 秒[/color][/del][color=green]用拳头击打目标，打断其正在施放的法术，并使其在4秒内不能施放该系法术。[/color]`
   
   这个主要是应对帖子花花绿绿比较瞎眼的问题
3. 部分雕文似乎被归类到通用技能里。例如：
   
   > 灵魂之井： ~~Your Soulwell glows with an eerie light.~~ 你的灵魂之井闪烁着诡异的光芒。
   
   这个技能的效果应该是一个术士雕文，而不是通用技能
4. 不应该对 m_auraDescription_lang 做 diff。例如：
   
   > 诡异魅影：在目标上方召唤一个诡异魅影，吸收25码范围内所有敌人的生命，在16秒内造成0点伤害，并为你进行治疗，治疗量相当于造成伤害的30%。
   > 
   > **每2秒对附近所有敌人造成伤害，并恢复施法的术士。**
   
   加粗部分为 m_auraDescription_lang 的描述，加入 diff 后反而会显得技能重复
5. 职业顺序应该按照 Blizzard 的常规顺序排列，即按照职业英文的字母序排列
6. 天赋解析有 BUG。例如
   
   > ~~金创药(被动天赋)：当一次伤害性攻击令你的生命值低于35%时，或当你受伤饮下酒时，会为你恢复15%的最大生命总值。该效果每30秒只能触发一次。~~
   > 
   > 散魔功：使你受到的魔法伤害降低60%，持续6秒。如果可能的话，还会将你身上当前激活的所有有害魔法效果返还给施法者。
   > 受到的法术伤害降低60%。
   
   从数据库里看应该是旧的金创药没了，多了一个新的金创药，法术 ID 不同。即应该是所谓的“技能重做”
7. 风火雷电(spell_id=137639)的数值有问题，rep_Spell 表为 155%，游戏内为 45%
8. 法术名不应该做分词 diff，而是直接 diff。要么不改要么认为全部改。例如：
   
   > ~~邪能弹幕~~ Fel ~~(NYI)~~ Barrage
   
   修改为
   
   > ~~邪能弹幕(NYI)~~ Fel Barrage
9. 天赋重做/替换/移动位置的问题
   
   希望可以修改成类似这样的效果：
   
   `剑刃风暴：重做\n[del]旧效果[/del]新效果`（法术 ID 变化但是法术名或**描述**没变，认为是重做）
   
   `嫁祸诀窍：被移除\n偷天换日：代替嫁祸诀窍\n偷天新效果`（同一个天赋槽完全换了一个技能，ID、名字、描述都不一样）
10. 部分技能有重复现象，需要修正。例如：
    
    > 怒击：用两把武器发动一次强力打击，总计造成[(230%武器伤害)+(230%武器伤害)]点物理伤害。只能在激怒状态下使用。产生5点怒气。 ]
    > 
    > 怒击：用两把武器发动一次强力打击，总计造成[(230%武器伤害)+(230%武器伤害)]点物理伤害。只能在激怒状态下使用。产生5点怒气。 ]
11. 需要开发一个人工的 blacklist，判断某些 diff 不算是真的 diff，比如纯标点符号改动。例如：
    
    > 怒击：用两把武器发动一次强力打击，总计造成[(230%武器伤害)+(230%武器伤害)]点物理伤害。只能在激怒状态下使用。产生5点怒气。 ]

除了风火雷电数值问题应该 assign 给 @swqsldz 以外，其他问题需要 @AeanSR 协助解决

如果对上述 issue 有疑问，可以在这里回复 ，注意注明序号

注意：**讨论后我们需要制定一下下一个版本的上线内容**

**Comment by AeanSR** [comment]
dcb27fa 解决了3, 4, 5, 8, 10。
1应当assign给公爵。
dbc_SkillLineAbility.field10重命名时请告知。

**Comment by AeanSR** [comment]
73306b2 解决了2。
6、9、11需要再讨论一下。我的意见是忠于数据库，数据库发生了什么变化，我们就体现什么变化，no more no less。天赋/PVP天赋可以再增加说明或者排序，来表现行列信息。

**Comment by AeanSR** [comment]
6bed1b8 解决了6

**Comment by icyblade** [comment]
11 需求取消。不给暴雪背锅

**Comment by swqsldz** [comment]
issue 1&7 fixed

**Comment by icyblade** [comment]
1,2,3,4,5,6,7,8,10 的解决方案将在 0.2.0 版本上线
