### ISSUE TITLE
0.1.0版本字段名替换

### ISSUE THREAD

**Issue by icyblade** [icyblade/aleph#2]
为保证代码可读性，需要对部分表的部分字段名做调整

希望 @swqsldz 可以直接在表结构定义里修改相关字段名，并重新灌一遍数据。保证当前版本及以后版本字段名全部是更新的

需要修改的表及其字段如下：

| 表名 | 原字段名 | 新字段名 |
| --- | --- | --- |
| dbc_JournalEncounter | field2 | m_name_lang |
| dbc_JournalEncounter | field3 | m_description_lang |
| dbc_JournalEncounter | field7 | m_journalInstanceID |
| dbc_JournalEncounter | field10 | m_orderIndex |
| dbc_JournalEncounterSection | field0 | m_title_lang |
| dbc_JournalEncounterSection | field1 | m_bodyText_lang |
| dbc_JournalEncounterSection | field2 | m_iconCreatureDisplayInfoID |
| dbc_JournalEncounterSection | field3 | m_spellID |
| dbc_JournalEncounterSection | field4 | m_iconFileDataID |
| dbc_JournalEncounterSection | field5 | m_journalEncounterID |
| dbc_JournalEncounterSection | field6 | m_nextSiblingSectionID |
| dbc_JournalEncounterSection | field7 | m_firstChildSectionID |
| dbc_JournalEncounterSection | field8 | m_parentSectionID |
| dbc_JournalEncounterSection | field9 | m_flags |
| dbc_JournalEncounterSection | field10 | m_iconFlags |
| dbc_JournalEncounterSection | field11 | m_orderIndex |
| dbc_JournalEncounterSection | field12 | m_type |
| dbc_JournalEncounterSection | field13 | m_difficultyMask |
| dbc_JournalInstance | field4 | m_name_lang |
| dbc_JournalInstance | field5 | m_description_lang |
| dbc_JournalTier | field0 | m_name_lang |
| dbc_JournalTierXInstance | field0 | m_journalTierID |
| dbc_JournalTierXInstance | field1 | m_journalInstanceID |
| dbc_SpellLineAbility | field9 | m_tradeSkillCategoryID |
| dbc_SpellLineAbility | field10 | m_acquireMethod |
| dbc_SpellLineAbility | field11 | m_numSkillUps |

**Comment by swqsldz** [comment]
fixed
