### ISSUE TITLE
0.2.0 版本 $ 的 parse 问题

### ISSUE THREAD

**Issue by icyblade** [icyblade/aleph#5]
**Def:** 第二个版本版本号为 0.2.0，对应原帖链接 [7.0.3.21531 - 7.0.3.21570 技能文本改动](http://bbs.ngacn.cc/read.php?tid=9260378)，对应原帖内容 [0.2.0.txt](https://github.com/icyblade/aleph/files/241038/0.2.0.txt)

这个版本里， 大量法术的 $ 部分 parse 的有问题。法术 ID 如下
- 193315 军刀猛刺
- 214579 响尾蛇
- 103985 猛虎式：wowhead 也是错的
- 185565 剧毒之刃：wowhead 也是错的
- 196103 绝对腐蚀
- 1719   战吼
- 190456 无视苦痛：wowhead 写的是 15*AP，这里是 (15+15*AP)*AP  

wowhead 错了的我们不管，不出意外锅是暴雪的。其他的需要解决

**Comment by icyblade** [comment]
- 1719 战吼，196103 绝对腐蚀

    dbc_Spell 原文没有标注百分比，但是游戏内和 wowhead 都有百分比
    
    怀疑是我们在解析 spellEffect 的时候漏掉了一个标注 basePoint 是不是百分比的 flag
    
- 190456 无视苦痛

    两个 AP 灰谷接锅，10/9 暴雪接锅。原文为：
    
    > 无视接下来受到的总计${$w1*10/9}点伤害中的$s2%，无论伤害来源是哪里

**Comment by AeanSR** [comment]
190456甩锅给公爵

    // dbc_Spell
    Fight through the pain, ignoring $s2% of the next ${$m1*$AP} damage you take from any sources.
    // rep_Spell
    Fight through the pain, ignoring 90% of the next [(15 + 1500%攻击强度)*攻击强度] damage you take from any sources.

**Comment by swqsldz** [comment]
1719，196103，216255做了单独fix，193315修正，214579增加特殊判断
190456 fix // min max 不计算成长
